### PR TITLE
Adds skip-regex option.

### PR DESCRIPTION
**Pull request by ryansmith94**
https://github.com/kucherenko/jscpd/issues/18

---
This change is [Reviewable](https://reviewable.io/reviews/kucherenko/jscpd/86)

### CODE REVIEW

**Comment by ryansmith94** [comment]
- Decreased code coverage is expected, I couldn't find your tests for CLI options.
- Travis build failing on older versions of Node, I guess that might also be expected.

**Comment by kucherenko** [comment]
Thank you for PR.
As I can see if I have duplication starts from 10 to 20 lines in code and I use ignore patterns before 10s line I will have wrong numbers on code lines in report, am I right?

**Comment by ryansmith94** [comment]
You're welcome. Yeah that's correct, not too sure what to do about that right now, I guess we could ensure that the regex ended with a line break and didn't replace the line break.

**Comment by aquid** [comment]
@kucherenko I would really be happy to see this getting merged. What needs to happen to get this merged?

**Comment by kucherenko** [comment]
@aquid I can't merge the PR because after that changes we will have wrong line numbers in report, I'm working on developing new generation of jscpd and will add this functionality

**Pull request closed without merging**
